--blank-lines-after-declarations
--blank-lines-after-procedures
-br  /* open braces on same line */
-nce /* start else on new line */
-nbc /* vars on same line */
-di8 /* line up var decl at col 8 */
-brs /* struct brace on same line */
-i8  /* indent 4  */
-lp  /* line up parens */
-ts8 /* tab stop */
-bbo /* break before && || */
-hnl /* honor newlines */
--space-special-semicolon
--line-length75
--dont-break-procedure-type
