os: Previous Visual Studio 2015

platform:
  - Win32
  - Win64

environment:
  CYG_ROOT: C:/cygwin
  CYG_SETUP_URL: http://www.cygwin.com/setup-x86.exe
  CYG_MIRROR: http://cygwin.mirror.constant.com
  CYG_CACHE: C:/cygwin/var/cache/setup

configuration:
  - Release

install:
  - ps:  echo "Installing Cygwin from $env:CYG_SETUP_URL to $env:CYG_ROOT/setup-x86.exe"
  - ps:  Invoke-WebRequest $env:CYG_SETUP_URL -OutFile $env:CYG_ROOT/setup-x86.exe
  - cmd: 'echo Installing Bison and Flex from Cygwin'
  - cmd: '%CYG_ROOT%\setup-x86.exe -qnNdO -R "%CYG_ROOT%" -s "%CYG_MIRROR%" -l "%CYG_CACHE%" -P bison -P flex > NUL'
  - cmd: 'echo Check Cygwin setup'
  - cmd: '%CYG_ROOT%/bin/bash -lc "cygcheck -dc cygwin"'
  - cmd: 'echo Done setting up Cygwin'
  - cmd: '%CYG_ROOT%/bin/flex --version'
  - cmd: '%CYG_ROOT%/bin/bison --version'

before_build:
  - if %platform%==Win32 set generator=Visual Studio 14 2015
  - if %platform%==Win64 set generator=Visual Studio 14 2015 Win64
  - if %platform%==Win32 set vcplatform=Win32
  - if %platform%==Win64 set vcplatform=x64

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "%generator%" -DBISON_EXECUTABLE=%CYG_ROOT%/bin/bison -DFLEX_EXECUTABLE=%CYG_ROOT%/bin/flex -DWITH_TESTS=1
  - msbuild flex.sln /p:Platform=%vcplatform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ctest -C %configuration%
