#ifndef OPTIONS_H
#define OPTIONS_H
#include "scanopt.h"

extern optspec_t flexopts[];

enum flexopt_flag_t {
    /* Use positive integers only, since they are return codes for scanopt.
     * Order is not important. */
    OPT_7BIT=1,
    OPT_8BIT,
    OPT_ALIGN,  OPT_NO_ALIGN,
    OPT_ALWAYS_INTERACTIVE,
    OPT_ARRAY,
    OPT_BACKUP,
    OPT_BATCH,
    OPT_CASE_INSENSITIVE,
    OPT_COMPRESSION,
    OPT_CPLUSPLUS,
    OPT_DEBUG,     OPT_NO_DEBUG,
    OPT_DEFAULT,   OPT_NO_DEFAULT,
    OPT_DONOTHING,
    OPT_ECS,       OPT_NO_ECS,
    OPT_FAST,
    OPT_FULL,
    OPT_HEADER,
    OPT_HELP,
    OPT_INTERACTIVE,
    OPT_LEX_COMPAT,
    OPT_MAIN,      OPT_NO_MAIN,
    OPT_META_ECS,  OPT_NO_META_ECS,
    OPT_NEVER_INTERACTIVE,
    OPT_NO_LINE,
    OPT_OUTFILE,
    OPT_PERF_REPORT,
    OPT_POINTER,
    OPT_PREFIX,
    OPT_PREPROCDEFINE,
    OPT_READ,
    OPT_REENTRANT,  OPT_NO_REENTRANT,
    OPT_REENTRANT_BISON,
    OPT_REJECT,  OPT_NO_REJECT,
    OPT_SKEL,
    OPT_STACK,
    OPT_STDINIT,
    OPT_STDOUT,
    OPT_TRACE,
    OPT_UNPUT,    OPT_NOUNPUT,
    OPT_VERBOSE,
    OPT_VERSION,
    OPT_WARN,     OPT_NO_WARN,
    OPT_YYCLASS,
    OPT_YYLINENO, OPT_NO_YYLINEO,
    OPT_YYMORE,   OPT_NO_YYMORE,
    OPT_YYWRAP,   OPT_NO_YYWRAP,

    OPT_YY_PUSH_STATE, OPT_NO_YY_PUSH_STATE,
    OPT_YY_POP_STATE,  OPT_NO_YY_POP_STATE,
    OPT_YY_TOP_STATE,  OPT_NO_YY_TOP_STATE,
    OPT_YY_SCAN_BUFFER,OPT_NO_YY_SCAN_BUFFER,
    OPT_YY_SCAN_BYTES, OPT_NO_YY_SCAN_BYTES,
    OPT_YY_SCAN_STRING,OPT_NO_YY_SCAN_STRING,
    OPT_YYGET_EXTRA,   OPT_NO_YYGET_EXTRA,
    OPT_YYSET_EXTRA,   OPT_NO_YYSET_EXTRA,
    OPT_YYGET_LENG,    OPT_NO_YYGET_LENG,
    OPT_YYGET_TEXT,    OPT_NO_YYGET_TEXT,
    OPT_YYGET_LINENO,  OPT_NO_YYGET_LINENO,
    OPT_YYSET_LINENO,  OPT_NO_YYSET_LINENO,
    OPT_YYGET_IN,      OPT_NO_YYGET_IN,
    OPT_YYSET_IN,      OPT_NO_YYSET_IN,
    OPT_YYGET_OUT,     OPT_NO_YYGET_OUT,
    OPT_YYSET_OUT,     OPT_NO_YYSET_OUT,
    OPT_YYGET_LVAL,    OPT_NO_YYGET_LVAL,
    OPT_YYSET_LVAL,    OPT_NO_YYSET_LVAL,
    OPT_YYGET_LLOC,    OPT_NO_YYGET_LLOC,
    OPT_YYSET_LLOC,    OPT_NO_YYSET_LLOC
};

#endif

/* vim:set tabstop=8 softtabstop=4 shiftwidth=4 textwidth=0: */
