
/* A lexical scanner generated by flex */

/* Target: C/C++ */
/* START of m4 controls */
/* 0 = 0 */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/*  */
/* test = test */
/*  */
/* END of m4 controls */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

#ifdef yy_create_buffer
#define test_create_buffer_ALREADY_DEFINED
#else
#define yy_create_buffer test_create_buffer
#endif

#ifdef yy_delete_buffer
#define test_delete_buffer_ALREADY_DEFINED
#else
#define yy_delete_buffer test_delete_buffer
#endif

#ifdef yy_scan_buffer
#define test_scan_buffer_ALREADY_DEFINED
#else
#define yy_scan_buffer test_scan_buffer
#endif

#ifdef yy_scan_string
#define test_scan_string_ALREADY_DEFINED
#else
#define yy_scan_string test_scan_string
#endif

#ifdef yy_scan_bytes
#define test_scan_bytes_ALREADY_DEFINED
#else
#define yy_scan_bytes test_scan_bytes
#endif

#ifdef yy_init_buffer
#define test_init_buffer_ALREADY_DEFINED
#else
#define yy_init_buffer test_init_buffer
#endif

#ifdef yy_flush_buffer
#define test_flush_buffer_ALREADY_DEFINED
#else
#define yy_flush_buffer test_flush_buffer
#endif

#ifdef yy_load_buffer_state
#define test_load_buffer_state_ALREADY_DEFINED
#else
#define yy_load_buffer_state test_load_buffer_state
#endif

#ifdef yy_switch_to_buffer
#define test_switch_to_buffer_ALREADY_DEFINED
#else
#define yy_switch_to_buffer test_switch_to_buffer
#endif

#ifdef yypush_buffer_state
#define testpush_buffer_state_ALREADY_DEFINED
#else
#define yypush_buffer_state testpush_buffer_state
#endif

#ifdef yypop_buffer_state
#define testpop_buffer_state_ALREADY_DEFINED
#else
#define yypop_buffer_state testpop_buffer_state
#endif

#ifdef yyensure_buffer_stack
#define testensure_buffer_stack_ALREADY_DEFINED
#else
#define yyensure_buffer_stack testensure_buffer_stack
#endif

#ifdef yylex
#define testlex_ALREADY_DEFINED
#else
#define yylex testlex
#endif

#ifdef yyrestart
#define testrestart_ALREADY_DEFINED
#else
#define yyrestart testrestart
#endif

#ifdef yylex_init
#define testlex_init_ALREADY_DEFINED
#else
#define yylex_init testlex_init
#endif

#ifdef yylex_init_extra
#define testlex_init_extra_ALREADY_DEFINED
#else
#define yylex_init_extra testlex_init_extra
#endif

#ifdef yylex_destroy
#define testlex_destroy_ALREADY_DEFINED
#else
#define yylex_destroy testlex_destroy
#endif

#ifdef yyget_debug
#define testget_debug_ALREADY_DEFINED
#else
#define yyget_debug testget_debug
#endif

#ifdef yyset_debug
#define testset_debug_ALREADY_DEFINED
#else
#define yyset_debug testset_debug
#endif

#ifdef yyget_extra
#define testget_extra_ALREADY_DEFINED
#else
#define yyget_extra testget_extra
#endif

#ifdef yyset_extra
#define testset_extra_ALREADY_DEFINED
#else
#define yyset_extra testset_extra
#endif

#ifdef yyget_in
#define testget_in_ALREADY_DEFINED
#else
#define yyget_in testget_in
#endif

#ifdef yyset_in
#define testset_in_ALREADY_DEFINED
#else
#define yyset_in testset_in
#endif

#ifdef yyget_out
#define testget_out_ALREADY_DEFINED
#else
#define yyget_out testget_out
#endif

#ifdef yyset_out
#define testset_out_ALREADY_DEFINED
#else
#define yyset_out testset_out
#endif

#ifdef yyget_leng
#define testget_leng_ALREADY_DEFINED
#else
#define yyget_leng testget_leng
#endif

#ifdef yyget_text
#define testget_text_ALREADY_DEFINED
#else
#define yyget_text testget_text
#endif

#ifdef yyget_lineno
#define testget_lineno_ALREADY_DEFINED
#else
#define yyget_lineno testget_lineno
#endif

#ifdef yyset_lineno
#define testset_lineno_ALREADY_DEFINED
#else
#define yyset_lineno testset_lineno
#endif

#ifdef yywrap
#define testwrap_ALREADY_DEFINED
#else
#define yywrap testwrap
#endif

#ifdef yyalloc
#define testalloc_ALREADY_DEFINED
#else
#define yyalloc testalloc
#endif

#ifdef yyrealloc
#define testrealloc_ALREADY_DEFINED
#else
#define yyrealloc testrealloc
#endif

#ifdef yyfree
#define testfree_ALREADY_DEFINED
#else
#define yyfree testfree
#endif

#ifdef yytext
#define testtext_ALREADY_DEFINED
#else
#define yytext testtext
#endif

#ifdef yyleng
#define testleng_ALREADY_DEFINED
#else
#define yyleng testleng
#endif

#ifdef yyin
#define testin_ALREADY_DEFINED
#else
#define yyin testin
#endif

#ifdef yyout
#define testout_ALREADY_DEFINED
#else
#define yyout testout
#endif

#ifdef yyflexdebug
#define testflexdebug_ALREADY_DEFINED
#else
#define yyflexdebug testflexdebug
#endif

#ifdef yylineno
#define testlineno_ALREADY_DEFINED
#else
#define yylineno testlineno
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* Feature test macros. Flex uses functions that require a minimum set of
 * macros defined. As defining some macros may hide function declarations that
 * user code might use, be conservative and respect user's definitions as much
 * as possible. In glibc, feature test macros may not be all set up until one
 * of the libc header (that includes <features.h>) is included. This creates
 * a circular dependency when we check the macros. <assert.h> is the safest
 * header we can include and does not declare too many functions we don't need.
 */
#if !defined(__GNU_LIBRARY__) && defined(__STDC__)
#include <assert.h>
#endif
#if !(defined(_POSIX_C_SOURCE) || defined(_XOPEN_SOURCE) || \
    defined(_POSIX_SOURCE))
# define _POSIX_C_SOURCE 1 /* Required for fileno() */
# define _POSIX_SOURCE 1
#endif
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* begin standard C++ headers. */

/* flex integer type definitions */

#ifndef YYFLEX_INTTYPES_DEFINED
#define YYFLEX_INTTYPES_DEFINED

/* Prefer C99 integer types if available. */

# if defined(__cplusplus) && __cplusplus >= 201103L
#include <cstdint>
#  define YYFLEX_USE_STDINT
# endif
# if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L
/* Include <inttypes.h> and not <stdint.h> because Solaris 2.6 has the former
 * and not the latter.
 */
#include <inttypes.h>
#  define YYFLEX_USE_STDINT
# else
#  if defined(_MSC_VER) && _MSC_VER >= 1600
/* Visual C++ 2010 does not define __STDC_VERSION__ and has <stdint.h> but not
 * <inttypes.h>.
 */
#include <stdint.h>
#   define YYFLEX_USE_STDINT
#  endif
# endif
# ifdef YYFLEX_USE_STDINT
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
# else
typedef unsigned char flex_uint8_t;
typedef short int flex_int16_t;
typedef unsigned short int flex_uint16_t;
#  ifdef __STDC__
typedef signed char flex_int8_t;
/* ISO C only requires at least 16 bits for int. */
#   ifdef __cplusplus
#include <climits>
#   else
#include <limits.h>
#   endif
#   if UINT_MAX >= 4294967295
#    define YYFLEX_INT32_DEFINED
typedef int flex_int32_t;
typedef unsigned int flex_uint32_t;
#   endif
#  else
typedef char flex_int8_t;
#  endif
#  ifndef YYFLEX_INT32_DEFINED
typedef long int flex_int32_t;
typedef unsigned long int flex_uint32_t;
#  endif
# endif
#endif /* YYFLEX_INTTYPES_DEFINED */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define yybegin(s) (yy_start) = 1 + 2 * (s)
/* Legacy interface */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define yystart() (((yy_start) - 1) / 2)
/* Legacy interfaces */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* The state buf must be large enough to hold one state per character in the main buffer,
 * plus the start state, plus the two end-of-buffer byte states.
 */
#define YY_STATE_BUF_EXTRA_SPACE 3
#define YY_STATE_BUF_SIZE   (YY_BUF_SIZE + YY_STATE_BUF_EXTRA_SPACE)

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *yybuffer;
/* Legacy interface */
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define yyunput(c) yyunput_r( c, (yytext_ptr)  )
/* Legacy interface */
#define unput(c) yyunput_r( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yyatbol;

	int yy_bs_lineno; /**< The line count. */
	int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static yybuffer * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define yy_current_buffer() ( (yy_buffer_stack)			\
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Legacy interface */
#define YY_CURRENT_BUFFER yy_current_buffer()
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( yybuffer new_buffer  );
yybuffer yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( yybuffer b  );
void yy_flush_buffer ( yybuffer b  );
void yypush_buffer_state ( yybuffer new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( yybuffer b, FILE *file  );
#define yy_flush_current_buffer() yy_flush_buffer( yy_current_buffer() )
#define YY_FLUSH_BUFFER yy_flush_current_buffer()

yybuffer yy_scan_buffer ( char *base, yy_size_t size  );
yybuffer yy_scan_string ( const char *yy_str  );
yybuffer yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) { \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
			yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
}
#define yysetbol(at_bol) \
	{ \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yyatbol = at_bol; \
}
#define yyatbol() (YY_CURRENT_BUFFER_LVALUE->yyatbol)
/* Legacy interface */
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yyatbol)
#define yy_set_bol(at_bol) \
	{ \
	if ( yy_current_buffer() == NULL ) { \
		yyensure_buffer_stack ();	\
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yyatbol = at_bol; \
}

/* Begin user sect3 */

#define testwrap() (/*CONSTCOND*/1)

#define YY_SKIP_YYWRAP

typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

/* Watch out: yytext_ptr is a variable when yytext is an array,
 * but it's a macro when yytext is a pointer.
 */

extern char *yytext;

#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

/* %% [1.5] DFA */
/* START of m4 controls */
/*  */
/*  */
/*  */
/* END of m4 controls */
/* START of Flex-generated definitions */#define YY_NUM_RULES 2
#define YY_END_OF_BUFFER 3
#define YY_JAMBASE 60
#define YY_JAMSTATE 32
#define YY_NUL_EC 1
#define YY_OFFSET_TYPE flex_int16_t 

/* END of Flex-generated definitions */

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yypanic ( const char* msg  );

struct yy_trans_info
	{
	/* We require that yy_verify and yy_nxt must be of the same size int. */

	/* We generate a bogus 'struct yy_trans_info' data type
	 * so we can guarantee that it is always declared in the skel.
	 * This is so we can compile "sizeof(struct yy_trans_info)"
	 * in any scanner.
	 */
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;

	};

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	do { \
	(yytext_ptr) = yy_bp; \
	 \
	yyleng = (int) (yy_cp - yy_bp); \
	 \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
 \
	(yy_c_buf_p) = yy_cp; \
	} while(0)

extern int yyflexdebug;
int yyflexdebug = 0;
/* Legacy interface */
#ifndef yy_flex_debug
#define yy_flex_debug yyflexdebug
#endif

/* %% [2.0] data tables for the DFA are inserted here */

/* footprint: 4471 bytes */
/* tblend: 66 */
/* numecs: 6 */
/* num_rules: 2 */
/* lastdfa: 31 */

/* m4 controls begin */
/*  */
/* m4 controls end */

static const flex_int16_t yy_accept[34] = { 0,

    1,     1,     1,     2,     3,     5,     5,     6,     7,     7, 
    7,     7,     7,     7,     7,     8,     8,     8,     8,     8, 
    8,     8,     8,     8,     8,     9,     9,     9,     9,     9, 
   10,    11,    11
};

/* Character equivalence-class mapping */
static const YY_CHAR yy_ec[256] = { 0,

    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     2, 
    3,     1,     1,     1,     1,     1,     1,     4,     4,     4, 
    4,     4,     4,     4,     4,     4,     4,     1,     1,     1, 
    1,     1,     1,     1,     5,     5,     5,     5,     5,     5, 
    5,     5,     5,     5,     5,     5,     5,     5,     5,     5, 
    5,     5,     5,     5,     5,     5,     5,     5,     5,     5, 
    1,     1,     1,     1,     5,     1,     5,     5,     5,     5, 

    5,     5,     5,     5,     5,     5,     5,     5,     5,     5, 
    5,     5,     5,     5,     5,     5,     5,     5,     5,     5, 
    5,     5,     6,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 

    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1,     1,     1,     1,     1,     1, 
    1,     1,     1,     1,     1
};

/* Character meta-equivalence-class mappings */
static const YY_CHAR yy_meta[7] = { 0,

    1,     2,     1,     1,     1,     1
};

static const flex_int16_t yy_acclist[11] = { 0,

    3,     2,     2, 16385, 16385, 16385,  8193,  8193,  8193,  8193
};

static const flex_int16_t yy_base[42] = { 0,

   54,    53,    57,    60,     0,     4,    51,     0,     6,     8, 
   49,    10,    51,    12,     0,    50,    14,    16,    18,    46, 
   20,    22,    24,    26,     0,    28,    45,    30,    44,     0, 
    0,    60,    33,    35,    37,     0,    39,    41,    43,    45, 
   47
};

static const flex_int16_t yy_def[42] = { 0,

   33,    33,    32,    32,    32,    34,     5,     5,    34,    35, 
    9,    35,    36,    37,     9,    36,    38,    37,    39,    18, 
   38,    40,    39,    41,    18,    40,    26,    41,    28,    26, 
   28,     0,    32,    32,    32,    32,    32,    32,    32,    32, 
   32
};

static const flex_int16_t yy_nxt[67] = { 0,

   16,     6,    32,     7,     8,    10,    11,    10,    11,    13, 
   14,    13,    14,    19,    20,    13,    22,    19,    20,    13, 
   24,    13,    22,    19,    27,    13,    24,    19,    29,    19, 
   27,    19,    29,     4,     4,     9,     9,    12,    12,    18, 
   18,    21,    21,    23,    23,    26,    26,    28,    28,    31, 
   30,    25,    17,    17,    15,     7,    32,     5,     5,     3, 
   32,    32,    32,    32,    32,    32
};

static const flex_int16_t yy_chk[67] = { 0,

   36,     5,     0,     5,     5,     6,     6,     9,     9,    10, 
   10,    12,    12,    14,    14,    17,    17,    18,    18,    19, 
   19,    21,    21,    22,    22,    23,    23,    24,    24,    26, 
   26,    28,    28,    33,    33,    34,    34,    35,    35,    37, 
   37,    38,    38,    39,    39,    40,    40,    41,    41,    29, 
   27,    20,    16,    13,    11,     7,     3,     2,     1,    32, 
   32,    32,    32,    32,    32,    32
};

#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000

/* Declare state buffer variables. */
static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static size_t yy_state_buf_max=0;
static char *yy_full_match;
static int yy_lp;

static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;

#define yyreject()				\
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
 \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
 \
++(yy_lp); \
goto find_rule; \
}
#define REJECT	yyreject()

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET

char *yytext;

/* %% [3.0] static declarations conditional on mode switches go here */
/*
 * This file is part of flex.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 
 * Neither the name of the University nor the names of its contributors
 * may be used to endorse or promote products derived from this software
 * without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND WITHOUT ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE.
 */
/* A template scanner file to build "scanner.cc". 
   The scanner tests that we correctly initialize the state buffer
   for long input buffers owned by code that calls yylex.
   
   This tests guards against reversions to CVE-2006-0459,
   in particular when variable trailing context rules are used. 
 */
#include <iostream>
#include <fstream>
#include <vector>

#define ECHO
/**
 * Balanced Bracketed Content.
 * May not contain bracket, but if it does then it is balanced.
 */

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */

#include <unistd.h>

#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_YYUNPUT
    
    static void yyunput_r ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_YYINPUT

static int yyinput ( void );
#ifndef __cplusplus
#define input yyinput
#endif

#endif

/*
 * Amount of stuff to slurp up with each read.
 * We assume the stdio library has already
 * chosen a fit size foe whatever platform
 * we're running on.
 */
#define YY_READ_BUF_SIZE BUFSIZ

/* Size of default input buffer. We want to be able to fit two
 * OS-level reads, but efficiency gains as the buffer size
 * increases fall off after that
 */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE	(2 * YY_READ_BUF_SIZE)
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef yyecho

/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define yyecho() do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)

#endif
/* Legacy interface */
#define ECHO yyecho()

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yypanic (const char* msg ) {
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Report a fatal error. Legacy interface. */
#ifndef YY_FATAL_ERROR

#define YY_FATAL_ERROR(msg) yypanic( msg )

#endif

/* Legacy interface */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) do {result = yyread(buf, max_size );} while (0)

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */

static int yyread(char *buf, size_t max_size ) {

	int result;
	
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) {
		int c = '*';
		yy_size_t n;
		for ( n = 0; n < max_size &&
			      (c = getc( yyin )) != EOF && c != '\n'; ++n ) {
			buf[n] = (char) c;
		}
		if ( c == '\n' ) {
			buf[n++] = (char) c;
		}
		if ( c == EOF && ferror( yyin ) ) {
			YY_FATAL_ERROR( "input in flex scanner failed" );
		}
		result = n;
	} else {
		errno=0;
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) {
			if( errno != EINTR) {
				YY_FATAL_ERROR( "input in flex scanner failed" );
				break;
			}
			errno=0;
			clearerr(yyin);
		}
	}

	 return result;
}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)

#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

#define YY_RULE_SETUP \
		YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL {
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) ) {
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) ) {
			(yy_start) = 1;	/* first start state */
		}
		if ( ! yyin ) {

			yyin = stdin;

		}
		if ( ! yyout ) {

			yyout = stdout;

		}
		if ( yy_current_buffer() == NULL ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		/* Create the reject buffer large enough to save one state per allowed character.
		 * If the reject buffer already exists, keep using it.
		 */
		if ( ! (yy_state_buf) ) {
			(yy_state_buf) = (yy_state_type *)yyalloc( ((YY_CURRENT_BUFFER_LVALUE->yy_buf_size + YY_STATE_BUF_EXTRA_SPACE) * sizeof(yy_state_type))  );
			if ( ! (yy_state_buf) ) {
				YY_FATAL_ERROR( "out of dynamic memory in yylex()" );
			}
			(yy_state_buf_max) = (YY_CURRENT_BUFFER_LVALUE->yy_buf_size + YY_STATE_BUF_EXTRA_SPACE);
		}

		yy_load_buffer_state(  );
	}

	/* open scope of user declarationns */
	{
/* %% [4.0] user's declarations go here */

		while ( /*CONSTCOND*/1 ) {		/* loops until end-of-file is reached */

			yy_cp = (yy_c_buf_p);

			/* Support of yytext. */
			*yy_cp = (yy_hold_char);

			/* yy_bp points to the position in yy_ch_buf of the start of
			 * the current run.
			 */
			yy_bp = yy_cp;

	/* Generate the code to find the start state. */

			yy_current_state = (yy_start);

			/* Set up for storing up states. */
			
			(yy_state_ptr) = (yy_state_buf);
			*(yy_state_ptr)++ = yy_current_state;

	yy_match:
			/* Generate the code to find the next match. */

			do {
				
	int yy_c = *(yy_ec+YY_SC_TO_UI(*yy_cp));
	/* Save the backing-up info \before/ computing the next state
	 * because we always compute one more state than needed - we
	 * always proceed until we reach a jam state
	 */
	
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state ) {
		yy_current_state = (int) yy_def[yy_current_state];

		/* We've arranged it so that templates are never chained
		 * to one another.  This means we can afford to make a
		 * very simple test to see if we need to convert to
		 * yy_c's meta-equivalence class without worrying
		 * about erroneously looking up the meta-equivalence
		 * class twice
		 */

		/* lastdfa + 2 == YY_JAMSTATE + 1 is the beginning of the templates */
		if (yy_current_state >= YY_JAMSTATE + 1) {
			yy_c = yy_meta[yy_c];
		}

	}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];

				*(yy_state_ptr)++ = yy_current_state;
				++yy_cp;

			}
			while ( yy_base[yy_current_state] != YY_JAMBASE );
			
	yy_find_action:
			/* code to find the action number goes here */
			
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
			for ( ; ; ) {	/* loop until we find out what rule we matched */
				if ((yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1]) {
					yy_act = yy_acclist[(yy_lp)];

					if ((yy_act & YY_TRAILING_HEAD_MASK) != 0 || (yy_looking_for_trail_begin)) {
						if (yy_act == (yy_looking_for_trail_begin)) {
							(yy_looking_for_trail_begin) = 0;
							yy_act &= ~YY_TRAILING_HEAD_MASK;
							break;
						}
					} else if (( yy_act & YY_TRAILING_MASK) != 0) {
						(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
						(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;

					} else {
						(yy_full_match) = yy_cp;
						(yy_full_state) = (yy_state_ptr);
						(yy_full_lp) = (yy_lp);
						break;
					}
					++(yy_lp);
				goto find_rule;

				}

				--yy_cp;

				/* We could consolidate the following two lines with those at
				 * the beginning, but at the cost of complaints that we're
				 * branching inside a loop.
				 */
				yy_current_state = *--(yy_state_ptr);
				(yy_lp) = yy_accept[yy_current_state];
			} /* close for */

			YY_DO_BEFORE_ACTION;

		do_action:	/* This label is used only to access EOF actions. */

			switch ( yy_act ) { /* beginning of action switch */

/* %% [5.0] user actions get inserted here */
	case 1:
/* rule 1 can match eol */
YY_RULE_SETUP

{
  return 1234;
}
	/*LINTED*/break;
	case 2:
YY_RULE_SETUP

yyecho();
	/*LINTED*/break;

case YY_STATE_EOF(INITIAL): /* FALLTHROUGH */
yyterminate();

			case YY_END_OF_BUFFER:
			{
				/* Amount of text matched not including the EOB char. */
				int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

				/* Undo the effects of YY_DO_BEFORE_ACTION. */
				*yy_cp = (yy_hold_char);
				YY_RESTORE_YY_MORE_OFFSET

				if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW ) {
					/* We're scanning a new file or input source.  It's
					 * possible that this happened because the user
					 * just pointed yyin at a new source and called
					 * yylex().  If so, then we have to assure
					 * consistency between yy_current_buffer() and our
					 * globals.  Here is the right place to do so, because
					 * this is the first action (other than possibly a
					 * back-up) that will match for the new input source.
					 */
					(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;

					YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;

					YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
				}

				/* Note that here we test for yy_c_buf_p "<=" to the position
				 * of the first EOB in the buffer, since yy_c_buf_p will
				 * already have been incremented past the NUL character
				 * (since all states make transitions on EOB to the
				 * end-of-buffer state).  Contrast this with the test
				 * in input().
				 */
				if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] ) { /* This was really a NUL. */
					yy_state_type yy_next_state;

					(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

					yy_current_state = yy_get_previous_state(  );

					/* Okay, we're now positioned to make the NUL
					 * transition.  We couldn't have
					 * yy_get_previous_state() go ahead and do it
					 * for us because it doesn't know how to deal
					 * with the possibility of jamming (and we don't
					 * want to build jamming into it because then it
					 * will run more slowly).
					 */

					yy_next_state = yy_try_NUL_trans( yy_current_state );

					yy_bp = (yytext_ptr) + YY_MORE_ADJ;

					if ( yy_next_state ) {
						/* Consume the NUL. */
						yy_cp = ++(yy_c_buf_p);
						yy_current_state = yy_next_state;
						goto yy_match;
					} else {
						
						/* Still need to initialize yy_cp, though
						 * yy_current_state was set up by
						 * yy_get_previous_state().
						 */
						yy_cp = (yy_c_buf_p);

						goto yy_find_action;
					}
				} else {	/* not a NUL */
					switch ( yy_get_next_buffer(  ) ) {
					case EOB_ACT_END_OF_FILE:
						(yy_did_buffer_switch_on_eof) = 0;

						if ( yywrap(  ) ) {
							/* Note: because we've taken care in
							 * yy_get_next_buffer() to have set up
							 * yytext, we can now set up
							 * yy_c_buf_p so that if some total
							 * hoser (like flex itself) wants to
							 * call the scanner after we return the
							 * YY_NULL, it'll still work - another
							 * YY_NULL will get returned.
							 */
							(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

							yy_act = YY_STATE_EOF(yystart());
							goto do_action;
						} else {
							if ( ! (yy_did_buffer_switch_on_eof) ) {
								YY_NEW_FILE;
							}
						}
						break;
					case EOB_ACT_CONTINUE_SCAN:
						(yy_c_buf_p) =
							(yytext_ptr) + yy_amount_of_matched_text;

						yy_current_state = yy_get_previous_state(  );

						yy_cp = (yy_c_buf_p);
						yy_bp = (yytext_ptr) + YY_MORE_ADJ;
						goto yy_match;

					case EOB_ACT_LAST_MATCH:
						(yy_c_buf_p) =
						&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

						yy_current_state = yy_get_previous_state(  );

						yy_cp = (yy_c_buf_p);
						yy_bp = (yytext_ptr) + YY_MORE_ADJ;
						goto yy_find_action;
					default:
						YY_FATAL_ERROR("unexpected return value from yy_get_next_buffer()");
					} /* end EOB inner switch */
				} /* end if */
				break;
			} /* case YY_END_OF_BUFFER */
			default:
				YY_FATAL_ERROR("fatal flex scanner internal error--no action found" );
			} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer (void)

{
		char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] ) {
		YY_FATAL_ERROR( "fatal flex scanner internal error--end of buffer missed" );
	}
	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 ) {
		/* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 ) {
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
		} else {
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
		}
	}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i ) {
		*(dest++) = *(source++);
	}
	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING ) {
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;
	} else {
		int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 ) { /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses yyreject()" );

		}

		if ( num_to_read > YY_READ_BUF_SIZE ) {
			num_to_read = YY_READ_BUF_SIZE;
		}
		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	if ( (yy_n_chars) == 0 ) {
		if ( number_to_move == YY_MORE_ADJ ) {
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
		} else {
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
		}
	} else {
		ret_val = EOB_ACT_CONTINUE_SCAN;
	}
	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1) + 2;
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf ) {
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		}
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state (void)

{
	yy_state_type yy_current_state;
	char *yy_cp;
	
	/* Generate the code to find the start state. */

			yy_current_state = (yy_start);

			/* Set up for storing up states. */
			
			(yy_state_ptr) = (yy_state_buf);
			*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp ) {
		/* Generate the code to find the next state. */
		
	int yy_c = (*yy_cp ? *(yy_ec+YY_SC_TO_UI(*yy_cp)) : YY_NUL_EC);
	/* Save the backing-up info \before/ computing the next state
	 * because we always compute one more state than needed - we
	 * always proceed until we reach a jam state
	 */
	
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state ) {
		yy_current_state = (int) yy_def[yy_current_state];

		/* We've arranged it so that templates are never chained
		 * to one another.  This means we can afford to make a
		 * very simple test to see if we need to convert to
		 * yy_c's meta-equivalence class without worrying
		 * about erroneously looking up the meta-equivalence
		 * class twice
		 */

		/* lastdfa + 2 == YY_JAMSTATE + 1 is the beginning of the templates */
		if (yy_current_state >= YY_JAMSTATE + 1) {
			yy_c = yy_meta[yy_c];
		}

	}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];

		*(yy_state_ptr)++ = yy_current_state;
	}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )

{
	int yy_is_jam;
		/* Generate code for handling NUL's, if needed. */

	/* First, deal with backing up and setting up yy_cp if the scanner
	 * finds that it should JAM on the NUL.
	 *
	 * Only generate a definition for "yy_cp" if we'll generate code
	 * that uses it.  Otherwise lint and the like complain.
	 */
	
	int yy_c = YY_NUL_EC;
	/* Save the backing-up info \before/ computing the next state
	 * because we always compute one more state than needed - we
	 * always proceed until we reach a jam state
	 */
	
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state ) {
		yy_current_state = (int) yy_def[yy_current_state];

		/* We've arranged it so that templates are never chained
		 * to one another.  This means we can afford to make a
		 * very simple test to see if we need to convert to
		 * yy_c's meta-equivalence class without worrying
		 * about erroneously looking up the meta-equivalence
		 * class twice
		 */

		/* lastdfa + 2 == YY_JAMSTATE + 1 is the beginning of the templates */
		if (yy_current_state >= YY_JAMSTATE + 1) {
			yy_c = yy_meta[yy_c];
		}

	}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];

yy_is_jam = (yy_current_state == YY_JAMSTATE);

	/* Only stack this state if it's a transition we
	 * actually make.  If we stack it on a jam, then
	 * the state stack and yy_c_buf_p get out of sync.
	 */
	if ( ! yy_is_jam ) {
		*(yy_state_ptr)++ = yy_current_state;
	}
	
		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_YYUNPUT
static void yyunput_r (int c, char * yy_bp )

{
	char *yy_cp;
	
	yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 ) {
		/* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf ) {
			*--dest = *--source;
		}
		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 ) {
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}
	}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif	/* ifndef YY_NO_YYINPUT */

#ifndef YY_NO_YYINPUT
int yyinput (void)

{
	int c;
	
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR ) {
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] ) {
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';
		} else {
			/* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) ) {
			case EOB_ACT_LAST_MATCH:
				/* This happens because yy_g_n_b()
				 * sees that we've accumulated a
				 * token and flags that we need to
				 * try matching the token before
				 * proceeding.  But for input(),
				 * there's no matching to consider.
				 * So convert the EOB_ACT_LAST_MATCH
				 * to EOB_ACT_END_OF_FILE.
				 */

				/* Reset buffer status. */
				yyrestart( yyin );

				/*FALLTHROUGH*/

			case EOB_ACT_END_OF_FILE:
				if ( yywrap(  ) ) {
					return 0;
				}
				if ( ! (yy_did_buffer_switch_on_eof) ) {
					YY_NEW_FILE;
				}
				return yyinput();

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) = (yytext_ptr) + offset;
				break;
			default:
				YY_FATAL_ERROR("unexpected return value from yy_get_next_buffer()");
			}
		}
	}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}

#endif	/* ifndef YY_NO_YYINPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */

void yyrestart  (FILE * input_file )

{
	
	size_t new_size = 0;
	yy_state_type *new_state_buf = 0;
 
	if ( yy_current_buffer() == NULL ) {
		yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
	        	yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER_LVALUE, input_file );
	yy_load_buffer_state(  );

	/* Ensure the reject state buffer is large enough.
	 */
	if ( (yy_state_buf_max) < (yy_size_t) (yy_current_buffer()->yy_buf_size + YY_STATE_BUF_EXTRA_SPACE) ) {
		new_size = yy_current_buffer()->yy_buf_size + YY_STATE_BUF_EXTRA_SPACE;
		new_state_buf = (yy_state_type *)yyrealloc( (yy_state_buf), (new_size * sizeof(yy_state_type))  );

		if ( new_state_buf == NULL ) {
			YY_FATAL_ERROR( "out of dynamic memory in yylex()" );
		}
		else {
			(yy_state_buf) = new_state_buf;
			(yy_state_buf_max) = new_size;
		}
	}
 
	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */

void yy_switch_to_buffer  (yybuffer  new_buffer )

{
	
	size_t new_size = 0;
	yy_state_type *new_state_buf = 0;
 
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
	 */
	yyensure_buffer_stack ();
	if ( yy_current_buffer() == new_buffer ) {
		return;
	}
	if ( yy_current_buffer() ) {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* Ensure the reject state buffer is large enough.
	 */
	if ( (yy_state_buf_max) < (yy_size_t) (YY_CURRENT_BUFFER_LVALUE->yy_buf_size + YY_STATE_BUF_EXTRA_SPACE) ) {
		new_size = YY_CURRENT_BUFFER_LVALUE->yy_buf_size + YY_STATE_BUF_EXTRA_SPACE;
		new_state_buf = (yy_state_type *)yyrealloc( (yy_state_buf), (new_size * sizeof(yy_state_type))  );

		if ( new_state_buf == NULL ) {
			YY_FATAL_ERROR( "out of dynamic memory in yylex()" );
		}
		else {
			(yy_state_buf) = new_state_buf;
			(yy_state_buf_max) = new_size;
		}
	}
 
	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)

{
		(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;

	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;

	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */

yybuffer yy_create_buffer  (FILE * file, int  size )

{
	yybuffer b;

	b = (yybuffer) yyalloc( sizeof( struct yy_buffer_state )  );
	if (  b == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
	}
	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( b->yy_ch_buf == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );
	}
	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */

void yy_delete_buffer (yybuffer  b )

{
	
	if ( b == NULL ) {
		return;
	}
	if ( b == yy_current_buffer() ) {	/* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (yybuffer) 0;
	}
	if ( b->yy_is_our_buffer ) {
		yyfree( (void *) b->yy_ch_buf  );
	}
	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */

static void yy_init_buffer  (yybuffer  b, FILE * file )

{
	int oerrno = errno;
	
	yy_flush_buffer( b );

	b->yy_input_file = file;

    /* b->yy_input_file should never by NULL but we'll handle it cleanly
	 * on the off chance.
	 */
	if (b->yy_input_file == NULL){
	  b->yy_fill_buffer = 0;
	} else {
	  b->yy_fill_buffer = 1;
	}

	/* If b is the current buffer, then yy_init_buffer was _probably_
	 * called from yyrestart() or through yy_get_next_buffer.
	 * In that case, we don't want to reset the lineno or column.
	 */
	if (b != yy_current_buffer()) {
		b->yy_bs_lineno = 1;
		b->yy_bs_column = 0;
	}

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c yy_current_buffer().
 * 
 */

void yy_flush_buffer (yybuffer  b )

{
		if ( b == NULL ) {
		return;
	}
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yyatbol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer() ) {
		yy_load_buffer_state(  );
	}
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */

void yypush_buffer_state (yybuffer new_buffer )

{
		if (new_buffer == NULL) {
		return;
	}
	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( yy_current_buffer() != NULL ) {
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
	}

	/* Only push if top exists. Otherwise, replace top. */
	if (yy_current_buffer()) {
		(yy_buffer_stack_top)++;
	}
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */

void yypop_buffer_state (void)

{
		if (yy_current_buffer() == NULL) {
		return;
	}
	yy_delete_buffer(yy_current_buffer() );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0) {
		--(yy_buffer_stack_top);
	}
	if (yy_current_buffer() != NULL) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */

static void yyensure_buffer_stack (void)

{
	yy_size_t num_to_alloc;
	
	if ((yy_buffer_stack) == NULL) {
		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
		 */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( (yy_buffer_stack == NULL) ) {
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
		}

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1) {
		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ((yy_buffer_stack) == NULL) {
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
		}
		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
yybuffer yy_scan_buffer  (char * base, yy_size_t  size )
{
	yybuffer b;
	
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR ) {
		/* They forgot to leave room for the EOB's. */
		return NULL;
	}
	b = (yybuffer) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( b == NULL ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );
	}
	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yyatbol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
yybuffer yy_scan_string (const char * yystr )
{
	
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
yybuffer yy_scan_bytes  (const char * yybytes, int  _yybytes_len ) {
	yybuffer b;
	char *buf;
	yy_size_t n;
	int i;
	
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( buf == 0 ) {
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );
	}
	for ( i = 0; i < _yybytes_len; ++i ) {
		buf[i] = yybytes[i];
	}
	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( b == NULL ) {
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );
	}
	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do { \
		/* Undo effects of setting up yytext. */ \
		int yyless_macro_arg = (n); \
		YY_LESS_LINENO(yyless_macro_arg);\
			yytext[yyleng] = (yy_hold_char); \
			(yy_c_buf_p) = yytext + yyless_macro_arg; \
			(yy_hold_char) = *(yy_c_buf_p); \
			*(yy_c_buf_p) = '\0'; \
			yyleng = yyless_macro_arg; \
	} while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void) {
	
	return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void) {
		return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void) {
		return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void) {
		return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void) {
		return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number ) {
	
	yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str ) {
		yyin = _in_str ;
}

void yyset_out (FILE *  _out_str ) {
		yyout = _out_str ;
}

int yyget_debug  (void) {
		return yyflexdebug;
}

void yyset_debug (int  _bdebug ) {
		yyflexdebug = _bdebug ;
}

static int yy_init_globals (void) {
		/* Initialization is the same as for the non-reentrant scanner.
	 * This function is called from yylex_destroy(), so don't allocate here.
	 */

	(yy_buffer_stack) = NULL;
	(yy_buffer_stack_top) = 0;
	(yy_buffer_stack_max) = 0;
	(yy_c_buf_p) = NULL;
	(yy_init) = 0;
	(yy_start) = 0;

	(yy_state_buf) = 0;
	(yy_state_ptr) = 0;
	(yy_state_buf_max) = 0;
	(yy_full_match) = 0;
	(yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
	yyin = stdin;
	yyout = stdout;
#else
	yyin = NULL;
	yyout = NULL;
#endif

	/* For future reference: Set errno on error, since we are called by
	 * yylex_init()
	 */
	return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void) {
	
	/* Pop the buffer stack, destroying each element. */
	while(yy_current_buffer()) {
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

	yyfree ( (yy_state_buf) );
	(yy_state_buf)  = NULL;

	/* Reset the globals. This is important in a non-reentrant scanner so the next time
	 * yylex() is called, initialization will occur. */
	yy_init_globals( );

	return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n ) {
		
	int i;
	for ( i = 0; i < n; ++i ) {
		s1[i] = s2[i];
	}
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size ) {
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size ) {
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr ) {
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

std::vector<char> readFile(const char* filename)
{
  std::vector<char> contents;
  std::ifstream     in(filename, std::ios::in | std::ios::binary);
  if (in)
  {
    in.seekg(0, std::ios::end);
    size_t size = static_cast<size_t>(in.tellg());
    contents.resize(size + 2);
    in.seekg(0, std::ios::beg);
    in.read(contents.data(), size);
    in.close();

    contents[size + 0] = '\0';
    contents[size + 1] = '\0';
  }
  else {
    std::cerr << "*** Error: std::ifstream(" << filename << ") failed." << std::endl;
    exit(-1);
  }
  return contents;
}

int main(int argc, char** argv)
{
  if ( argc != 2 ) {
    std::cerr << "*** Error: Must specify one filename." << std::endl;
    exit(-1);
  }

  std::vector<char> stm = readFile( argv[1] );
  test_scan_buffer(stm.data(), stm.size());

  testlex();
  
  std::vector<char> stm2(stm);
  stm2.insert(stm2.end(), stm.begin(), stm.end());
  test_scan_buffer(stm2.data(), stm2.size());

  testlex();

  return 0; // All went well.
}

