#! /bin/sh
# Test %yydecl option of flex in any cpp-based back end

trap 'rm /tmp/td$$' EXIT HUP INT QUIT TERM 
cat >/tmp/td$$ <<EOF
%option yydecl=int foobar(void)"
%%
%%
EOF

( ../src/flex -t /tmp/td$$  | grep "#define YY_DECL int foobar(void)" >/dev/null ) || (echo "%yydecl test failed." >&2; exit 1)



